### ISSUE TITLE
Posicionamento de textos

### ISSUE THREAD

**Issue by carlosbremer95** [hugogzz93/heynavi_front#4]
<img width="799" alt="Screen Shot 2023-02-27 at 16 46 02" src="https://user-images.githubusercontent.com/126524743/221703614-96e9b890-f6df-483b-a546-f6f2df6843f7.png">

La info esta diferente posicionada.

**Comment by carlosbremer95** [comment]
<img width="620" alt="Screen Shot 2023-02-27 at 16 49 55" src="https://user-images.githubusercontent.com/126524743/221704683-5f3baaa4-eb80-49c0-8b77-f42370f6d5c3.png">

Hay manera que el texto sea responsiva sin importar el tamaño de la pantalla?

**Comment by carlosbremer95** [comment]
<img width="529" alt="Screen Shot 2023-02-27 at 16 54 53" src="https://user-images.githubusercontent.com/126524743/221706460-08e9af06-3f1f-4523-a8fa-242a1351f847.png">

**Comment by hugogzz93** [comment]
En que pantalla es esto? Lo habia tratado con iphone y no sucedia asi.

**Comment by carlosbremer95** [comment]
version web cuando haces la pantalla mas chica

**Comment by carlosbremer95** [comment]
<img width="535" alt="Screen Shot 2023-02-27 at 17 09 05" src="https://user-images.githubusercontent.com/126524743/221710010-4d95dc4d-eeda-40db-b6f3-758f3aea1686.png">
<img width="417" alt="Screen Shot 2023-02-27 at 17 08 45" src="https://user-images.githubusercontent.com/1265
<img width="408" alt="Screen Shot 2023-02-27 at 17 08 13" src="https://user-images.githubusercontent.com/126524743/221710039-b244ec22-6453-4c90-b240-39d4ef4b7afa.png">
24743/221710020-63e74d96-fc20-497b-8881-8a4ab68f54ad.png">

Perdon por el bombardeo de sc pero tambien en estas versiones esta raro como se ve el texto
- Iphone 12
- Ipad Mini y Ipad Air 
- Surface Pro
- Nest Hub

**Comment by hugogzz93** [comment]
Listo, ya no deberia de suceder.
Porfavor intenta de nuevo.

96689b3 debio de resolver esto.

**Comment by hugogzz93** [comment]
> <img alt="Screen Shot 2023-02-27 at 16 46 02" width="799" src="https://user-images.githubusercontent.com/126524743/221703614-96e9b890-f6df-483b-a546-f6f2df6843f7.png">
> 
> La info esta diferente posicionada.

En cuanto a esto: no es tanto un bug, es que simplemente es mucho texto para el espacio. 
Vamos a tener que pensar en algo, igual y que se use un font mas pequeno, pero bueno, esto lo dejaria para una segunda iteracion. ie. improvements.

Que opinas @diegovali1 ?

**Comment by hugogzz93** [comment]
Lo voy a cerrar, porque hay issues que si se corrigieron.
Mejor hacer otro issue especificamente para esto.
