### ISSUE TITLE
Landing Page Mobile: Posición de imagenes

### ISSUE THREAD

**Issue by diegovali1** [hugogzz93/heynavi_front#7]
La posición de la chava viene distinto al figma. En el figma viene la chava apuntandole al recuadro de "Analizamos..."

Versión mobile (Iphone 14):

![IMG_0701](https://user-images.githubusercontent.com/126524143/221711507-a9484683-f289-4aab-9e3c-c172318befd6.PNG)

Versión Figma:
<img width="376" alt="Screenshot 2023-02-27 at 17 21 17" src="https://user-images.githubusercontent.com/126524143/221711684-10737769-4751-4696-9e41-b8339ac8bd9c.png">

**Comment by hugogzz93** [comment]
Este lo cambie de lado porque ya con las diferentes pantallas, quedaba mejor del lado izquierdo en mobil.
Yo creo que mejor dejarlo para otra entrega. 

Tambien el boton esta arriba en vez de abajo como en figma.

Esos dos detalles me tomaria un rato mas y prefiero no detener la entrega.
